const comidas = [
  {
    idMeal: '52844',
    strMeal: 'Lasagne',
    strDrinkAlternate: null,
    strCategory: 'Pasta',
    strArea: 'Italian',
    strInstructions: 'Heat the oil in a large saucepan. Use kitchen scissors to snip',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=gfhfsBPt46s',
    strIngredient1: 'Olive Oil',
    strIngredient2: 'Bacon',
    strIngredient3: 'Onion',
    strIngredient4: 'Celery',
    strIngredient5: 'Carrots',
    strIngredient6: 'Garlic',
    strIngredient7: 'Minced Beef',
    strIngredient8: 'Tomato Puree',
    strIngredient9: 'Chopped Tomatoes',
    strIngredient10: 'Honey',
    strIngredient11: 'Lasagne Sheets',
    strIngredient12: 'Creme Fraiche',
    strIngredient13: 'Mozzarella Balls',
    strIngredient14: 'Parmesan Cheese',
    strIngredient15: 'Basil Leaves',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 tblsp ',
    strMeasure2: '2',
    strMeasure3: '1 finely chopped ',
    strMeasure4: '1 Stick',
    strMeasure5: '1 medium',
    strMeasure6: '2 cloves chopped',
    strMeasure7: '500g',
    strMeasure8: '1 tbls',
    strMeasure9: '800g',
    strMeasure10: '1 tblsp ',
    strMeasure11: '500g',
    strMeasure12: '400ml',
    strMeasure13: '125g',
    strMeasure14: '50g',
    strMeasure15: 'Topping',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbcgoodfood.com/recipes/classic-lasagne',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: '52785',
    strMeal: 'Dal fry',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Indian',
    strInstructions: 'Wash and soak toor dal in approx. 3 cups of water, for at least ',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
    strTags: 'Curry',
    strYoutube: 'https://www.youtube.com/watch?v=J4D855Q9-jg',
    strIngredient1: 'Toor dal',
    strIngredient2: 'Water',
    strIngredient3: 'Salt',
    strIngredient4: 'Turmeric',
    strIngredient5: 'Ghee',
    strIngredient6: 'Chopped tomatoes',
    strIngredient7: 'Cumin seeds',
    strIngredient8: 'Mustard Seeds',
    strIngredient9: 'Bay Leaf',
    strIngredient10: 'Green Chili',
    strIngredient11: 'Ginger',
    strIngredient12: 'Cilantro',
    strIngredient13: 'Red Pepper',
    strIngredient14: 'Salt',
    strIngredient15: 'Sugar',
    strIngredient16: 'Garam Masala',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 cup',
    strMeasure2: '2-1/2 cups',
    strMeasure3: '1 tsp',
    strMeasure4: '1/4 tsp',
    strMeasure5: '3 tbs',
    strMeasure6: '1 cup',
    strMeasure7: '1/2 tsp',
    strMeasure8: '1/2 tsp',
    strMeasure9: '2',
    strMeasure10: '1 tbs chopped',
    strMeasure11: '2 tsp shredded',
    strMeasure12: '2 tbs ',
    strMeasure13: '1/2 tsp',
    strMeasure14: '1/2 tsp',
    strMeasure15: '1 tsp',
    strMeasure16: '1/4 tsp',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.instagram.com/p/BO21bpYD3Fu',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

export default comidas;
