const comidas = [
  {
    idMeal: '52977',
    strMeal: 'Corba',
    strDrinkAlternate: null,
    strCategory: 'Side',
    strArea: 'Turkish',
    strInstructions: 'Pick through your lentils for any foreign debris, rinse them 2 or',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
    strTags: 'Soup',
    strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
    strIngredient1: 'Lentils',
    strIngredient2: 'Onion',
    strIngredient3: 'Carrots',
    strIngredient4: 'Tomato Puree',
    strIngredient5: 'Cumin',
    strIngredient6: 'Paprika',
    strIngredient7: 'Mint',
    strIngredient8: 'Thyme',
    strIngredient9: 'Black Pepper',
    strIngredient10: 'Red Pepper Flakes',
    strIngredient11: 'Vegetable Stock',
    strIngredient12: 'Water',
    strIngredient13: 'Sea Salt',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 cup ',
    strMeasure2: '1 large',
    strMeasure3: '1 large',
    strMeasure4: '1 tbs',
    strMeasure5: '2 tsp',
    strMeasure6: '1 tsp ',
    strMeasure7: '1/2 tsp',
    strMeasure8: '1/2 tsp',
    strMeasure9: '1/4 tsp',
    strMeasure10: '1/4 tsp',
    strMeasure11: '4 cups ',
    strMeasure12: '1 cup ',
    strMeasure13: 'Pinch',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  { idMeal: '52978',
    strMeal: 'Kumpir',
    strDrinkAlternate: null,
    strCategory: 'Side',
    strArea: 'Turkish',
    strInstructions: 'If you order kumpir in Turkey, the standard filling is first, lots',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
    strTags: 'SideDish',
    strYoutube: 'https://www.youtube.com/watch?v=IEDEtZ4UVtI',
    strIngredient1: 'Potatoes',
    strIngredient2: 'Butter',
    strIngredient3: 'Cheese',
    strIngredient4: 'Onion',
    strIngredient5: 'Red Pepper',
    strIngredient6: 'Red Chile Flakes',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 large',
    strMeasure2: '2 tbs',
    strMeasure3: '150g',
    strMeasure4: '1 large',
    strMeasure5: '1 large',
    strMeasure6: 'Pinch',
    strMeasure7: ' ',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  { idMeal: '53026',
    strMeal: 'Tamiya',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Egyptian',
    strInstructions: 'oak the beans in water to cover overnight.Drain. If skinless beans',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
    strIngredient1: 'Broad Beans',
    strIngredient2: 'Spring Onions',
    strIngredient3: 'Garlic Clove',
    strIngredient4: 'Parsley',
    strIngredient5: 'Cumin',
    strIngredient6: 'Baking Powder',
    strIngredient7: 'Cayenne Pepper',
    strIngredient8: 'Flour',
    strIngredient9: 'Vegetable Oil',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '3 cups ',
    strMeasure2: '6',
    strMeasure3: '4',
    strMeasure4: '1/4 cup',
    strMeasure5: '2 tsp',
    strMeasure6: '1 tsp ',
    strMeasure7: '1/2 tsp',
    strMeasure8: 'Spinkling',
    strMeasure9: 'As required',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  { idMeal: '52785',
    strMeal: 'Dal fry',
    strDrinkAlternate: null,
    strCategory: 'Vegetarian',
    strArea: 'Indian',
    strInstructions: 'Wash and soak toor dal in approx. 3 cups of water, for at least ',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
    strTags: 'Curry,Vegetarian,Cake',
    strYoutube: 'https://www.youtube.com/watch?v=J4D855Q9-jg',
    strIngredient1: 'Toor dal',
    strIngredient2: 'Water',
    strIngredient3: 'Salt',
    strIngredient4: 'Turmeric',
    strIngredient5: 'Ghee',
    strIngredient6: 'Chopped tomatoes',
    strIngredient7: 'Cumin seeds',
    strIngredient8: 'Mustard Seeds',
    strIngredient9: 'Bay Leaf',
    strIngredient10: 'Green Chili',
    strIngredient11: 'Ginger',
    strIngredient12: 'Cilantro',
    strIngredient13: 'Red Pepper',
    strIngredient14: 'Salt',
    strIngredient15: 'Sugar',
    strIngredient16: 'Garam Masala',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 cup',
    strMeasure2: '2-1/2 cups',
    strMeasure3: '1 tsp',
    strMeasure4: '1/4 tsp',
    strMeasure5: '3 tbs',
    strMeasure6: '1 cup',
    strMeasure7: '1/2 tsp',
    strMeasure8: '1/2 tsp',
    strMeasure9: '2',
    strMeasure10: '1 tbs chopped',
    strMeasure11: '2 tsp shredded',
    strMeasure12: '2 tbs ',
    strMeasure13: '1/2 tsp',
    strMeasure14: '1/2 tsp',
    strMeasure15: '1 tsp',
    strMeasure16: '1/4 tsp',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.instagram.com/p/BO21bpYD3Fu',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

export default comidas;
