// data[newFoodRecipe.Id]
const foodRecipe = {
  info: {
    Id: 'idMeal',
    Name: '',
    DrinkAlternate: '',
    Category: '',
    Area: '',
    MealThumb: '',
    Tags: '',
    Youtube: '',
    Source: '',
    ImageSource: '',
    CreativeCommonsConfirmed: '',
    dateModified: '',
  },
  Instructions: '',
  Igredients: {
    Ingredient1: '',
    Ingredient2: '',
    Ingredient3: '',
    Ingredient4: '',
    Ingredient5: '',
    Ingredient6: '',
    Ingredient7: '',
    Ingredient8: '',
    Ingredient9: '',
    Ingredient10: '',
    Ingredient11: '',
    Ingredient12: '',
    Ingredient13: '',
    Ingredient14: '',
    Ingredient15: '',
    Ingredient16: '',
    Ingredient17: '',
    Ingredient18: '',
    Ingredient19: '',
    Ingredient20: '',
    Measure1: '',
    Measure2: '',
    Measure3: '',
    Measure4: '',
    Measure5: '',
    Measure6: '',
    Measure7: '',
    Measure8: '',
    Measure9: '',
    Measure10: '',
    Measure11: '',
    Measure12: '',
    Measure13: '',
    Measure14: '',
    Measure15: '',
    Measure16: '',
    Measure17: '',
    Measure18: '',
    Measure19: '',
    Measure20: '',
  },
};

export default foodRecipe;
